name: Update KO1 English Players

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go get -v ./...

      - name: Fetch existing gh-pages branch (if it exists)
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch found"

      - name: Create a temporary directory to store JSON files
        run: mkdir -p json_files

      - name: Check out the JSON files from gh-pages branch if it exists
        run: |
          # Check out the gh-pages branch (if it exists)
          git checkout origin/gh-pages -- last-online-players.json || echo "No previous last-online-players.json found"
          git checkout origin/gh-pages -- recent-players.json || echo "No previous recent-players.json found"
          # Move the JSON files to a temporary directory if they exist
          [ -f last-online-players.json ] && mv last-online-players.json json_files/
          [ -f recent-players.json ] && mv recent-players.json json_files/
        continue-on-error: true

      - name: Run Go scraper
        env:
          LAST_ONLINE_PLAYERS: json_files/last-online-players.json
          RECENT_PLAYERS: json_files/recent-players.json
        run: go run ./cmd/ko1-eng-players

      # Create a clean gh-pages branch with only index.html, internal/ui folder, and JSON files
      - name: Deploy to gh-pages
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

          # Switch to a new clean gh-pages branch
          git checkout --orphan gh-pages

          # Move index.html, internal/ui folder, and JSON files to a safe location
          mkdir -p ./deploy/ui
          cp -r ./internal/ui/* ./deploy/ui/  # Copy the UI files to the deploy folder
          cp index.html ./deploy/             # Copy index.html to the deploy folder
          cp json_files/last-online-players.json ./deploy/ || echo "No previous last-online-players.json found"
          cp json_files/recent-players.json ./deploy/ || echo "No previous recent-players.json found"

          # Remove all tracked files
          git rm -rf .

          # Move index.html, internal/ui, and the JSON files back from the deploy folder
          mv ./deploy/index.html ./index.html
          mv ./deploy/last-online-players.json ./last-online-players.json || echo "No previous last-online-players.json found"
          mv ./deploy/recent-players.json ./recent-players.json || echo "No previous recent-players.json found"
          mkdir -p ./internal/ui
          mv ./deploy/ui/* ./internal/ui/     # Move the UI files back to internal/ui

          # Clean up deploy folder
          rm -rf ./deploy

          # Add the required files to the gh-pages branch
          git add index.html
          git add last-online-players.json
          git add recent-players.json
          git add internal/ui

          # Commit and force push to the gh-pages branch
          git commit -m "Update players list and JSON files"
          git push origin gh-pages --force

      # Remove temporary JSON directory after files have been deployed
      - name: Clean up json_files directory
        run: rm -rf ./json_files
