name: Update KO1 English Players

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go get -v ./...

    - name: Run Go scraper
      run: go run ./cmd/ko1-eng-players

    - name: Commit and push to gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Use the GitHub Actions token for authentication
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git checkout -B gh-pages                 # Force create or switch to gh-pages
        git add index.html                       # Stage the generated index.html
        git commit -m "Update players list"      # Commit the changes
        git push origin gh-pages --force         # Force-push to gh-pages branch