name: Update KO1 English Players

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go get -v ./...

    - name: Fetch existing gh-pages branch (if it exists)
      run: |
        git fetch origin gh-pages || echo "No gh-pages branch found"

    # If gh-pages exists, restore previous JSON files
    - name: Restore previous JSON files
      run: |
        git checkout gh-pages -- last-online-players.json || echo "No previous last-online-players.json found"
        git checkout gh-pages -- recent-players.json || echo "No previous recent-players.json found"
      continue-on-error: true

    - name: Run Go scraper
      run: go run ./cmd/ko1-eng-players

    # Create a clean gh-pages branch with only index.html, internal/ui folder, and JSON files
    - name: Deploy to gh-pages
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        
        # Switch to a new clean gh-pages branch
        git checkout --orphan gh-pages
        
        # Move index.html, internal/ui folder, and JSON files to a safe location
        mkdir -p ./deploy/ui
        cp -r ./internal/ui/* ./deploy/ui/  # Copy the UI files to the deploy folder
        cp index.html ./deploy/             # Copy index.html to the deploy folder
        cp last-online-players.json ./deploy/   # Copy last-online-players.json to the deploy folder
        cp recent-players.json ./deploy/    # Copy recent-players.json to the deploy folder
        
        # Remove all tracked files
        git rm -rf .
        
        # Move index.html, internal/ui, and the JSON files back from the deploy folder
        mv ./deploy/index.html ./index.html
        mv ./deploy/last-online-players.json ./last-online-players.json || echo "No previous last-online-players.json found"
        mv ./deploy/recent-players.json ./recent-players.json || echo "No previous recent-players.json found"
        mkdir -p ./internal/ui
        mv ./deploy/ui/* ./internal/ui/     # Move the UI files back to internal/ui
        
        # Clean up deploy folder
        rm -rf ./deploy
        
        # Add the required files to the gh-pages branch
        git add index.html
        git add last-online-players.json
        git add recent-players.json
        git add internal/ui
        
        # Commit and force push to the gh-pages branch
        git commit -m "Update players list and JSON files"
        git push origin gh-pages --force